### ISSUE TITLE
PyroSession.__init__() got an unexpected keyword argument 'date'

### ISSUE THREAD

**Issue by dprosan** [shamhi/NotCoinBot#21]
PyroSession.__init__() got an unexpected keyword argument 'date'

Traceback (most recent call last):
  File "C:\Users\dpros\NotCoinBot\main.py", line 17, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\dpros\NotCoinBot\main.py", line 9, in main
    await start_process(logger=logger)
  File "C:\Users\dpros\NotCoinBot\bot\utils\launcher.py", line 105, in start_process
    clients = await get_clients(session_files=session_files)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dpros\NotCoinBot\bot\utils\launcher.py", line 68, in get_clients
    clients = [Client(
              ^^^^^^^^
  File "C:\Users\dpros\NotCoinBot\bot\utils\launcher.py", line 72, in <listcomp>
    session_string=(await get_session_string(session_name=session_name)),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dpros\NotCoinBot\bot\utils\launcher.py", line 54, in get_session_string
    raise InvalidSession(session_name)
bot.exceptions.InvalidSession: test

**Comment by THMaST3R** [comment]
same issue

**Comment by shamhi** [comment]
okey, i will fix it

**Comment by dprosan** [comment]
thank u very much, everything works, u are the best!
