### ISSUE TITLE
FileNotFoundError: Not found session files

### ISSUE THREAD

**Issue by hagl327** [shamhi/NotCoinBot#28]
Установка по инструкции из README.
В .env заполнил API_ID и API_HASH
Запускаю docker compose up, вижу следующее:
```
(venv) NotCoinBot ❯ docker compose up                                                                                                                                      main
[+] Building 0.0s (0/0)                                                                                                                       docker-container:insecure-builder
[+] Running 1/0
 ✔ Container NotCoin-bot  Created                                                                                                                                          0.0s
Attaching to NotCoin-bot
NotCoin-bot  | 07:44:59 | INFO     | 86 - Обнаружено 0 сессий / 0 прокси
NotCoin-bot  |
NotCoin-bot  | Traceback (most recent call last):
NotCoin-bot  |   File "/app/main.py", line 17, in <module>
NotCoin-bot  |     asyncio.run(main())
NotCoin-bot  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
NotCoin-bot  |     return loop.run_until_complete(main)
NotCoin-bot  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
NotCoin-bot  |     return future.result()
NotCoin-bot  |   File "/app/main.py", line 9, in main
NotCoin-bot  |     await start_process(logger=logger)
NotCoin-bot  |   File "/app/bot/utils/launcher.py", line 110, in start_process
NotCoin-bot  |     clients = await get_clients(session_files=session_files)
NotCoin-bot  |   File "/app/bot/utils/launcher.py", line 58, in get_clients
NotCoin-bot  |     raise FileNotFoundError("Not found session files")
NotCoin-bot  | FileNotFoundError: Not found session files
```
Без докера получаю такую же ошибку, моя версия Python 3.10.12.

**Comment by hagl327** [comment]
Не создал сессию, чтобы ее создать при запуске main.py нужно прописать 1 и далее ответить на вопросы бота.
