### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by GoDL1ghT** [shamhi/NotCoinBot#31]
Питон версии 3.12.2. Всё сделал по инструкции, но не запускается.

(venv) PS C:\Users\Gleb\Desktop\NotCoinBot-main> python main.py
Traceback (most recent call last):
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\main.py", line 4, in <module>
    from bot.utils.logging import logger
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\bot\utils\__init__.py", line 1, in <module>
    from .eval_js import eval_js
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\bot\utils\eval_js.py", line 1, in <module>
    from js2py import eval_js as js_eval
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gleb\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by shamhi** [comment]
откати питон до 3.11 или 3.10
