### ISSUE TITLE
bot does not start or work after starting on telegram and /stat or /balance returns this error

### ISSUE THREAD

**Issue by lord-dubious** [shamhi/NotCoinBot#32]
Object does not exist
Traceback (most recent call last):
  File "/home/dark/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/dark/Desktop/NotCoinBot/bot/plugins/nc_manage.py", line 73, in send_stats
    start_balance = await get_start_balance(session_id=session_id)
  File "/home/dark/Desktop/NotCoinBot/db/functions.py", line 102, in get_start_balance
    stat = await Statistic.get(session=session)
  File "/usr/local/lib/python3.10/dist-packages/tortoise/queryset.py", line 1020, in _execute
    raise DoesNotExist("Object does not exist")
tortoise.exceptions.DoesNotExist: Object does not exist

**Comment by shamhi** [comment]
you need to start bot with command /click on, before send /stat or /balance

**Comment by lord-dubious** [comment]
did that already the bot is frozen after /click on and stays like that forever

**Comment by shamhi** [comment]
to stop the bot after /click on, you need to send /click off instead of pressing Ctrl+C

**Comment by lord-dubious** [comment]
the bot does not even start it stays hooked when you use the start command

**Comment by shamhi** [comment]
> the bot does not even start it stays hooked when you use the start command

try to delete config/database.db and run bot

**Comment by lord-dubious** [comment]
1. Создать сессию
2. Запустить бота С возможностью управления через телеграмм
3. Запустить бота БЕЗ возможности управления через телеграмм
Выберите ваше действие: 2

14:57:31 | INFO     | 103 - Бот запущен на 1 сессиях.
Отправьте /help в чате Избранное/Saved Messages 

14:57:58 | INFO     | 38 - Кликер запущен командой /click on




i re installed the bot

**Comment by lord-dubious** [comment]
it is still stuck here

**Comment by lord-dubious** [comment]
> 1. Создать сессию
> 2. Запустить бота С возможностью управления через телеграмм
> 3. Запустить бота БЕЗ возможности управления через телеграмм
>    Выберите ваше действие: 2
> 
> 14:57:31 | INFO | 103 - Бот запущен на 1 сессиях. Отправьте /help в чате Избранное/Saved Messages
> 
> 14:57:58 | INFO | 38 - Кликер запущен командой /click on
> 
> i re installed the bot

config/database.db  does not even get created

**Comment by shamhi** [comment]
problem is different, check your time on PC, if it's wrong, bot won't work

**Comment by lord-dubious** [comment]
im using vps

**Comment by shamhi** [comment]
well, try to uncomment this lines and run
![image](https://github.com/shamhi/NotCoinBot/assets/148555284/379a1216-7a0b-4ac6-b692-1fc7b86eb36d)

**Comment by lord-dubious** [comment]
1. Создать сессию
2. Запустить бота С возможностью управления через телеграмм
3. Запустить бота БЕЗ возможности управления через телеграмм
Выберите ваше действие: 2

16:06:32 | INFO     | 103 - Бот запущен на 1 сессиях.
Отправьте /help в чате Избранное/Saved Messages 

INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.session:Session initialized: Layer 158
INFO:pyrogram.session.session:Device: CPython 3.10.12 - Pyrogram 2.0.106
INFO:pyrogram.session.session:System: Linux 5.2.0 (en)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.client:[dubious] [LOAD] MessageHandler("get_notcoin_url") in group 0 from "bot.plugins.nc_manage"
INFO:pyrogram.client:[dubious] [LOAD] MessageHandler("launch_clicker") in group 0 from "bot.plugins.nc_manage"
INFO:pyrogram.client:[dubious] [LOAD] MessageHandler("send_help_text") in group 0 from "bot.plugins.nc_manage"
INFO:pyrogram.client:[dubious] [LOAD] MessageHandler("send_my_balance") in group 0 from "bot.plugins.nc_manage"
INFO:pyrogram.client:[dubious] [LOAD] MessageHandler("send_stats") in group 0 from "bot.plugins.nc_manage"
INFO:pyrogram.client:[dubious] Successfully loaded 5 plugins from "bot/plugins"
INFO:pyrogram.dispatcher:Started 10 HandlerTasks
16:07:01 | INFO     | 38 - Кликер запущен командой /click on

**Comment by lord-dubious** [comment]
16:15:30 | WARNING  | 447 - dubious | Доступ к API запрещен: 403
16:15:30 | INFO     | 448 - dubious | Сплю 35 сек

**Comment by lord-dubious** [comment]
note i am using residential proxies

**Comment by shamhi** [comment]
try to use another proxy
