### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by ShitCodeTech** [shamhi/NotCoinBot#33]
python3 main.py
22:36:46 | INFO     | 85 - Обнаружено 1 сессий / 0 прокси

1. Создать сессию
2. Запустить бота С возможностью управления через телеграмм
3. Запустить бота БЕЗ возможности управления через телеграмм
Выберите ваше действие: 2

Traceback (most recent call last):
  File "/root/NotCoinBot/main.py", line 20, in <module>
    run_async(main())
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/tortoise/__init__.py", line 688, in run_async
    loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/NotCoinBot/main.py", line 12, in main
    await start_process(logger=logger)
  File "/root/NotCoinBot/bot/utils/launcher.py", line 101, in start_process
    tg_clients = await get_clients(session_names=session_names)
  File "/root/NotCoinBot/bot/utils/launcher.py", line 71, in get_clients
    await check_sessions(session_names=session_names, tg_clients=tg_clients)
  File "/root/NotCoinBot/db/functions.py", line 33, in check_sessions
    async with client:
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/client.py", line 311, in __aenter__
    return await self.start()
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/client.py", line 616, in load_session
    await self.storage.open()
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/storage/file_storage.py", line 63, in open
    self.update()
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/storage/file_storage.py", line 52, in update
    self.version(version)
  File "/root/NotCoinBot/venv/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 219, in version
    self.conn.execute(
sqlite3.OperationalError: database is locked

**Comment by shamhi** [comment]
you have another process running that is blocking the session file.
