### ISSUE TITLE
error

### ISSUE THREAD

**Issue by arm4xlll** [shamhi/NotCoinBot#34]
Traceback (most recent call last):
  File "C:\Users\bb\NotCoinBot\main.py", line 20, in <module>
    run_async(main())
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\tortoise\__init__.py", line 688, in run_async
    loop.run_until_complete(coro)
  File "C:\Users\bb\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\bb\NotCoinBot\main.py", line 12, in main
    await start_process(logger=logger)
  File "C:\Users\bb\NotCoinBot\bot\utils\launcher.py", line 109, in start_process
    tg_clients = await get_clients(session_names=session_names)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bb\NotCoinBot\bot\utils\launcher.py", line 71, in get_clients
    await check_sessions(session_names=session_names, tg_clients=tg_clients)
  File "C:\Users\bb\NotCoinBot\db\functions.py", line 33, in check_sessions
    async with client:
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\pyrogram\methods\utilities\start.py", line 68, in start
    await self.invoke(raw.functions.updates.GetState())
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 86, in invoke
    await self.fetch_peers(getattr(r, "users", []))
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\pyrogram\client.py", line 531, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "C:\Users\bb\NotCoinBot\venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 129, in update_peers
    self.conn.executemany(
sqlite3.OperationalError: table peers has no column named username

**Comment by arm4xlll** [comment]
fixed
