### ISSUE TITLE
Помогите пожалуйста

### ISSUE THREAD

**Issue by HachBoB** [shamhi/NotCoinBot#7]
(venv) C:\Users\Kostya\Desktop\NotCoinBot-main>python .\main.py
Traceback (most recent call last):
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\main.py", line 13, in <module>
    from core import create_sessions, start_farming
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\core\__init__.py", line 2, in <module>
    from .start_farming import start_farming
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\core\start_farming.py", line 27, in <module>
    from utils import eval_js, read_session_json_file
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\utils\__init__.py", line 1, in <module>
    from .eval_js import eval_js
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\utils\eval_js.py", line 1, in <module>
    from js2py import eval_js as js_eval
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostya\Desktop\NotCoinBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by shamhi** [comment]
ошибка связана с библиотекой js2py
проверьте, установлен ли у вас [nodejs](https://nodejs.org/en/download) и если нет, то установите

**Comment by mytab0r** [comment]
1. Лучше использовать poetry(так хоть будет понятно какую версию питона юзаешь)
2. если ты сидишь на 3.12, сделай даунгрейд на 3.11 - Мне помогло
