### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by xlangzhong1** [shamhi/NotCoinBot#9]
its error
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 161, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1001611131299'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\client.py", line 596, in handle_updates
    channel=await self.resolve_peer(utils.get_channel_id(channel_id)),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 111, in resolve_peer
    await self.invoke(
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 87, in invoke
    await self.fetch_peers(getattr(r, "chats", []))
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\client.py", line 558, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "F:\github\NotCoinBot\venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 138, in update_peers
    self.conn.execute(
sqlite3.OperationalError: database is locked`

**Comment by shamhi** [comment]
https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked
